[book]
authors = ["Kurt Pan"]
language = "zh-TW"
src = "src"
title = "密碼戰爭"

[output.html]
theme = "theme"
additional-css = ["theme/custom-fonts.css"]
default-theme = "light"
preferred-dark-theme = "light"

[output.html.search]
enable = false

[output.html.print]
enable = true

[output.html.fold]
enable = true   # whether or not to enable section folding
level = 0        # the depth to start folding